version: '3'
services:
  node-server:
    image: rakd/weavedb-node-server
    # build:
    #   context: ./node-server
    #   dockerfile: standalone.Dockerfile
    ports:
      - "9090:9090"
      - "4736:4736"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./node-server/cache:/weavedb/cache
      # to sync weavedb settings
      # - ./node-server/weavedb.standalone.config.js:/weavedb/grpc-node/node-server/weavedb.standalone.config.js
      # - ./node-server/weavedb.config.js:/weavedb/grpc-node/node-server/weavedb.config.js
      - ./node-server/conf:/weavedb/conf
  envoy:
    image: rakd/weavedb-envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    environment:
      - LISTEN_PORT=8080
      - ADMIN_LISTEN_PORT=9901
      - SERVICE_DISCOVERY_ADDRESS=node-server
      - SERVICE_DISCOVERY_PORT=9090
