version: '3'
services:
  node-server:
    build:
      context: .
      dockerfile: standalone.Dockerfile
    ports:
      - "9090:9090"
      - "4736:4736"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./cache:/weavedb/cache
      # to sync weavedb settings
      - ./conf:/weavedb/grpc-node/node-server/conf

  envoy:
    build: ../envoy
    ports:
      - "8080:8080"
    volumes:
      # to sync envoy settings 
      - ../envoy/conf:/etc/envoy
