version: '3'
services:
  node-server:
    build:
      context: .
      dockerfile: standalone.Dockerfile
    ports:
      - "9090:9090"
      - "4736:4736"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./cache:/weavedb/cache
      # to sync weavedb settings
      - ./conf:/weavedb/grpc-node/node-server/conf

  envoy:
    build: ../envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
    environment:
      - LISTEN_PORT=8080
      - ADMIN_LISTEN_PORT=9901
      - SERVICE_DISCOVERY_ADDRESS=0.0.0.0
      - SERVICE_DISCOVERY_PORT=9090

