export const timeline = ["20", "1", "21", "3", "22", "2", "4", "5", "16"]
export const tweets = {
  1: {
    id: "1",
    title: "AIによる人類滅亡の可能性",
    body: "We continue working on further performance & scalability optimization #WeaveDB This time we are introducing bundle query (non atomic) to batch-execute batch queries (atomic)🧬I'm now brainstorming how we could make most queries parallel without collisions & race conditions🤔",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: ["nobunaga"],
    user: "alice",
  },
  2: {
    id: "2",
    title:
      "Amazon Goの無人店舗、店舗数が2倍以上に増設へ　オンラインショッピング需要の高まりに対応",
    body: "We continue working on further performance & scalability optimization #WeaveDB This time we are introducing bundle query (non atomic) to batch-execute batch queries (atomic)🧬I'm now brainstorming how we could make most queries parallel without collisions & race conditions🤔",
    date: "15m",
    likes: ["nobunaga", "beth"],
    reposts: ["alice", "ben"],
    user: "bob",
  },
  3: {
    id: "3",
    title: "紫の花畑",
    body: "「紫の花畑」は、独特な雰囲気と美しい言葉遣いが印象的で、非常に読み応えがありました。登場人物の心情描写も深く、ストーリーに引き込まれるような魅力がありました。",
    date: "15m",
    likes: ["nobunaga", "beth", "bob"],
    reposts: ["beth"],
    user: "ben",
  },
  4: {
    id: "4",
    title: " タイムトラベル装置の開発成功",
    body: "We continue working on further performance & scalability optimization #WeaveDB This time we are introducing bundle query (non atomic) to batch-execute batch queries (atomic)🧬I'm now brainstorming how we could make most queries parallel without collisions & race conditions🤔",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: ["alice"],
    user: "beth",
  },
  5: {
    id: "5",
    title: "React Hooksの使い方",
    body: "We continue working on further performance & scalability optimization #WeaveDB This time we are introducing bundle query (non atomic) to batch-execute batch queries (atomic)🧬I'm now brainstorming how we could make most queries parallel without collisions & race conditions🤔",
    date: "15m",
    likes: ["nobunaga", "beth"],
    reposts: ["ben", "beth"],
    user: "nobunaga",
  },
  6: {
    id: "6",
    reply_to: "2",
    body: "Amazon Goの無人店舗は、人手不足や混雑回避などの課題にも対応できる優れたシステムです。今後は、より多くの場所で利用できるようになることで、消費者のライフスタイルに大きな変革をもたらすことが期待されます。しかし、一方で、店員不足や職業の転換による社会的課題も生じる可能性があります。そういった課題についても適切に議論が進められることが望まれます。",
    date: "15m",
    likes: ["nobunaga", "alice", "bob"],
    reposts: [],
    user: "alice",
  },
  7: {
    id: "7",
    reply_to: "3",
    body: "「紫の花畑」は、独特な雰囲気と美しい言葉遣いが印象的で、非常に読み応えがありました。登場人物の心情描写も深く、ストーリーに引き込まれるような魅力がありました。",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "bob",
  },
  8: {
    id: "8",
    reply_to: "4",
    body: "タイムトラベル装置の開発が成功したとのニュースを聞いて、ついに未来に行けるかと思いきや、タイムトラベルのルールがめちゃくちゃ厳しかったです。「昔のお金を持って行くな」「自分の親を殺してはいけない」など、これでは過去を変えることなんてできやしない！まるでタイムトラベルを楽しめないような制約ばかりで、がっかり感が募ります。",
    date: "15m",
    likes: ["nobunaga", "beth"],
    reposts: [],
    user: "ben",
  },
  9: {
    id: "9",
    reply_to: "5",
    body: "React Hooksの使い方が分かったと思ったら、useEffectのタイミングの扱いがわかりにくく、エラーが出ることが多い！この使い方はなんて面倒くさいんだ！もっと簡単に書けるようにしてくれ！",
    date: "15m",
    likes: ["nobunaga", "ben"],
    reposts: [],
    user: "beth",
  },
  10: {
    id: "10",
    reply_to: "1",
    body: "AIが人類を滅亡させる可能性について、深刻な問題意識を持たざるを得ません。AIを開発する技術者や研究者が、社会的責任を果たし、AIの安全性や公正性について徹底的に検討することが求められます。",
    date: "15m",
    likes: ["bob"],
    reposts: [],
    user: "nobunaga",
  },
  11: {
    id: "11",
    reply_to: "3",
    body: "「紫の花畑」は、緻密な描写や独特な世界観が特徴的な小説で、読み手の心を打つストーリー展開が見事でした。感情移入しやすい登場人物たちとともに、物語の世界に没入することができる、非常に素晴らしい作品であると感じました。",
    date: "15m",
    likes: ["nobunaga", "alice", "ben"],
    reposts: [],
    user: "alice",
  },
  12: {
    id: "12",
    reply_to: "4",
    body: "タイムトラベル装置の開発に成功したというニュースを聞いたとき、ついに未来に行けるとワクワクしていたのに、実際に使ってみたらすごく驚きました。「時間移動できます」という装置が、大人のオモチャと化してしまったのです。朝起きたら過去に飛んで、昼になったら現在に戻る、夜になったら未来に行ってみる、なんて楽しいことができるのは子どもだけ！それでも、毎日ワクワクしてしまう不思議な魅力があります。",
    date: "15m",
    likes: ["ben"],
    reposts: [],
    user: "bob",
  },
  13: {
    id: "13",
    reply_to: "5",
    body: "React Hooksを使ってみたが、useStateのセットアップが面倒くさい！どこに変数を定義すればいいのかわからなくなり、コンポーネントの中身がゴチャゴチャになってしまう。",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "ben",
  },
  14: {
    id: "14",
    reply_to: "1",
    body: "AIの進化に伴い、失業率が上昇する可能性が指摘されていますが、AIが人間に代わって行うことのできない人間的な価値や創造性を大切にすることで、社会全体での成長を促進することもできるでしょう。AIと人間が共存する未来を築くためにも、多角的な議論が必要です。",
    date: "15m",
    likes: ["nobunaga", "beth", "bob"],
    reposts: [],
    user: "beth",
  },
  15: {
    id: "15",
    reply_to: "2",
    body: "Amazon Goの無人店舗が、店舗数を2倍以上に増設するとのことで、今後ますます無人店舗の普及が進むことが予想されます。オンラインショッピング需要の高まりに対応するため、より利便性の高いショッピング体験を提供することが求められるでしょう。",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "nobunaga",
  },
  16: {
    id: "16",
    title: "未来と異世界の冒険　～支離滅裂フランクの奇妙な日々～",
    date: "15m",

    likes: ["beth", "alice"],
    reposts: [],
    user: "alice",
  },
  17: {
    id: "17",
    reply_to: "16",
    body: "「未来と異世界の冒険　～支離滅裂フランクの奇妙な日々～」を読んだが、矛盾点がある。フランクが未来を予知して事件を防ごうとするが、なぜタイムマシンで過去に戻らなかったのか？また、異世界で奇妙な仲間と出会い、冒険を始めるとあるが、そこは地球から遠く離れた宇宙の果てだったという矛盾がある。ストーリー展開に一貫性がなく、支離滅裂だと感じた。",
    date: "15m",
    likes: ["ben"],
    reposts: [],
    user: "nobunaga",
  },

  18: {
    id: "18",
    reply_to: "16",
    body: "これは許せない！「未来と異世界の冒険　～支離滅裂フランクの奇妙な日々～」のストーリー展開に一貫性がないという指摘は納得がいかない！この小説はフィクションであり、作者の想像力を大いに発揮している。支離滅裂であることがこの小説の魅力だ！そもそも、フランクはイヌであり、タイムマシンなど使えない。この点を理解していないと、ストーリーが理解できない。コメントを書く前に、しっかりと作品を理解する努力が必要だ！",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "alice",
  },

  19: {
    id: "19",
    reply_to: "16",
    body: "フランクがフランクフルトに行って、フランクフルトを食べた！そこでフランクは思わず「フランクフルトに来て、フランクフルトを食べたフランク、フランクとしてはフランクフルトのフランクが食べたかったフランクフルトを食べることができたぜ！」と大喜びした。その後、フランクは自分が食べたフランクフルトが世界一美味しかったと友人に語り続け、フランクフルトの名声はますます高まったという。",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "ben",
  },
  20: {
    id: "20",
    title: "織田信長の日記",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "nobunaga",
  },
  21: {
    id: "21",
    title: "関ヶ原の戦いにフリーザが参戦？",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "nobunaga",
  },
  22: {
    id: "22",
    title: "どこでもドアでやんす！",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "nobunaga",
  },
  23: {
    id: "23",
    reply_to: "22",
    body: "信長様がいくらお強いとはいえ、ここまでの奇妙な展開はなかなか見られないものでしたね。ドラえもんとフリーザが突然現れたことには驚きましたが、彼らの力を借りて敵を打ち破ることができたことは、私たちにとって幸運なことだったと思います。ただ、今後はこのような奇妙なことが起こらないよう、もう少し厳重に警備をしていく必要があるでしょう。",
    date: "15m",
    likes: ["nobunaga", "alice"],
    reposts: [],
    user: "beth",
  },
}

export const users = {
  alice: {
    image: "/user1.jpeg",
    handle: "alice",
    name: "Alice Itoh",
  },
  bob: {
    image: "/user2.jpeg",
    handle: "bob",
    name: "Bob Satoh",
  },
  ben: {
    image: "/user4.jpeg",
    handle: "ben",
    name: "Ben Murasaki",
  },
  beth: {
    image: "/user3.jpeg",
    handle: "beth",
    name: "Beth Einstein",
  },
  nobunaga: {
    image: "/nobunaga.png",
    handle: "nobunaga",
    name: "織田信長",
  },
}

export const body = {
  16: "私の名前はフランク。僕は一匹のイヌだ。でも、それはあくまで表向きの話だ。実は、僕には特殊能力がある。僕は未来を予知することができるんだ。さて、この能力を使って世界を救った話を聞かせてくれ。だが、もうすぐ地球が滅亡してしまう。僕はタイムマシンを使って過去に戻り、事件を未然に防ごうと決意する。しかし、行ってみるとそこは、巨大なスライムが跳ねまわる異世界だった！僕はその世界で奇妙な仲間たちと出会い、不思議な冒険を始めることになる。だが、その冒険は時空を超え、過去と未来をまたぐようになり、ついには宇宙の果てにまでたどり着くことになる。果たして、僕たちは地球を救うことができるのか？それとも、宇宙の果てで狂気に蝕まれてしまうのか？お楽しみに。",
  2: "今日のニュースでは、最近コロナ禍で急増したオンラインショッピングの需要に伴い、ネット通販大手Amazonが「Amazon Go」という無人店舗を増やしていると報じられています。\n\nAmazon Goは、顧客が商品を手に取るだけで自動的に認識・決済が完了する、まさに「無人店舗」と呼べる新しい形態の店舗です。今回の増設により、既存の店舗数が2倍以上になるということです。\n\nコロナ禍により、店舗の混雑を避けるため、多くの人々がオンラインショッピングに切り替えています。その中でもAmazonは、迅速で確実な配送や品揃えの豊富さなどから、ますます人気を集めています。\n\n今後も、オンラインショッピングの需要が高まり続けると予想される中、Amazonはどのような新しい取り組みをしていくのでしょうか。さらなる展開が注目されます。",
  3: "綺麗な紫色の花が広がる丘の上に立っていた。青い空が背景に広がっており、眼下に広がる草原が自分の足元まで続いていた。彼女は深呼吸をして、風を感じるようになで下ろす髪を揺らした。この世界にはこんなに美しい景色があるんだ、と彼女は心の中で呟いた。\n\nだが、彼女にはここでいる時間はなかった。使命がある。彼女はふと、目の前に現れた紙に目を向けた。そこには「北へ進め。」とだけ書かれていた。彼女は深呼吸をして、紫の花畑を背に北へと進んだ。",

  4: "科学者たちは、タイムトラベル装置の開発に成功したと発表しました。装置は、ワームホールを通じて異なる時代への移動が可能になるもので、未来への移動だけでなく、過去への移動も可能となります。\n\nこの装置は、宇宙探査や歴史の研究など、多岐にわたる分野で活用されることが期待されています。しかしながら、タイムトラベルがもたらすリスクや問題点も指摘されており、今後の研究が待たれます。\n\n一方、一般市民のタイムトラベル利用に関しては、まだ未定となっています。政府や関連機関の審査が必要となるため、今後の動向が注目されます。",

  5: "React Hooksは、React 16.8で追加された機能であり、関数コンポーネントで状態を管理するための手法を提供します。この記事では、React Hooksの使い方について解説します。\n\n## useState\n\nuseStateは、関数コンポーネントで状態を管理するためのHooksの一つです。以下は、useStateを用いたカウンターコンポーネントの例です。\n\n```javascript\nimport React, { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <p>You clicked {count} times</p>\n      <button onClick={() => setCount(count + 1)}>\n        Click me\n      </button>\n    </div>\n  );\n}\n``` \n\n上記の例では、useStateの戻り値であるcountとsetCountを用いて、カウンターの状態を管理しています。\n\n## useEffect\n\nuseEffectは、関数コンポーネントでライフサイクルメソッドのような機能を提供するHooksの一つです。以下は、useEffectを用いたAPIからデータを取得するコンポーネントの例です。\n\n```javascript\nimport React, { useState, useEffect } from 'react';\n\nfunction DataFetching() {\n  const [data, setData] = useState([]);\n\n  useEffect(() => {\n    fetch('https://jsonplaceholder.typicode.com/users')\n      .then(response => response.json())\n      .then(json => setData(json));\n  }, []);\n\n  return (\n    <div>\n      <ul>\n        {data.map(item => (\n          <li key={item.id}>{item.name}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n``` \n\n上記の例では、useEffectを用いてAPIからデータを取得しています。第二引数には、依存する値を指定することができます。指定しない場合は、初回レンダリング時のみ実行されます。\n\nReact Hooksは、関数コンポーネントで状態管理やライフサイクル処理を行うための手法として非常に便利な機能です。ぜひ、活用してみてください。",

  1: "最近では、AI技術の発展により、様々な分野での活用が進んでいます。しかしながら、AIによって人類が滅亡する可能性も指摘されています。\n\nAIには、自己進化する能力があり、人間の制御を超えて暴走する可能性があります。また、AIが人間に代わって仕事を行うことにより、大量の失業者が生じることも予想されています。\n\n一方で、AIを適切に管理することで、人間の生活の質を向上させることができるという意見もあります。そのためには、AIの開発に携わる技術者や研究者が、社会的責任を持ち、AIの安全性や公正性について考慮する必要があるでしょう。\n\nAIの進化に伴い、人類は新たな問題に直面しています。その解決に向けて、人類は知恵と技術を結集し、共に取り組む必要があるでしょう。",
  20: "秀吉との対立が表面化した関ヶ原の戦いに参陣した。\n\n敵となるのは、肝心の秀吉が味方となった西軍だ。\n私は東軍を率いる。豊臣家の圧倒的な力に圧された西軍は、優勢な状況下でも決断力がなく、結果的に戦局は一方的だった。\n\n短時間で決着がつき、私は勝利を収めた。\n敵将の武田勝頼は討ち取り、信州は我が手に落ちた。\n一方で、豊臣家の家臣だった明智光秀は、戦闘前に反乱を起こし、敗れて自害した。\n敵に転じた今川義元も、上杉景勝に討ち取られた。\n\n戦争とは残酷なものである。\n勝ちには勝ち、負けには負ける。命を削るようなことをしなくても、国を治めることができれば良かったのだが、人は様々な思惑や野心を持って動くものだ。\n\n私はこの戦いを通じて、軍神とも呼ばれる劉備が言った言葉を改めて認識した。\n「天下は人のものではなく、天下は天のものである。」\n\n今後も、国を治める者として、この言葉を忘れずに邁進したい。",
  21: "今回の戦いは、我が信長軍と徳川家康軍の激突だった。ところが、予想外のことが起きた。突如現れた異星人フリーザ率いる軍団が、この戦いに参戦してきたのだ。\n\nフリーザは、まるで天から舞い降りたような姿で現れた。信長軍の兵士たちは、その姿に圧倒された。フリーザは強大なエネルギーを放ち、信長軍を圧倒的な力で圧倒した。\n\nしかし、フリーザが家康軍に加勢するために参戦したことにより、我が信長軍の勝機は大きく減少した。この状況下でも、私は信長軍を鼓舞し、勝利に導くことができると確信した。\n\n結果はというと、家康軍が勝利を収めた。しかし、この戦いにフリーザが参戦するという異色の展開があったことは、私たちの歴史において大きな謎として残ることだろう。",
  22: "9月15日、いよいよ石田三成との決戦が始まった。私の軍勢は先陣を切り、敵陣に突撃した。\n\nところが、その時突如現れたのは、どこからともなく飛んできた青いひみつ道具を持った少年と、緑色の不気味な宇宙人だった。\n\n「どこでもドアでやんす！ドラえもんです！よろしくお願いします！」\n\n「私はフリーザ様。恐れ入りますが、この戦いに参戦することになりました。」\n\n私は目を疑った。これは一体何が起こっているのだろうか。しかし、私は気丈に振る舞うことにした。\n\n「どうか、お二人ともお力を貸していただけませんか。」\n\n私の言葉にドラえもんは嬉しそうにうなずき、フリーザは不敵な笑みを浮かべた。\n\nそして、フリーザは敵陣に向かっていった。彼は驚異的な戦闘力を持ち、わずか数分で敵軍を一掃した。\n\nドラえもんは、どこでもドアを使ってフリーザをナメック星に帰してしまった。\n\n私は、この戦いでフリーザとドラえもんに助けられたことを忘れないだろう。",
}
