[package]
name = "weavedb"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.18"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rocksdb = "0.21"
clap = { version = "4", features = ["derive"] }
deno_core = "0.273.0"
http = "1.3.1"
rsa = { version = "0.9.8", features = ["pem"] }
sha2 = "0.10.9"
base64 = "0.22.1"
http-sig = "0.6"
hex = "0.4.3"
openssl = { version = "0.10.72", features = ["vendored"] }
rayon = "1.10.0"
reqwest = { version = "0.12.15", features = ["json"] }
thiserror = "2.0.12"
