[package]
name = "weavedb"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.18"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rocksdb = "0.21"
clap = { version = "4", features = ["derive"] }
deno_core = "0.273.0"