module.exports = {
  posts: {
    type: "object",
    required: ["owner", "id"],
    properties: {
      id: { type: "string", pattern: "^[0-9a-z]{32,32}$" },
      owner: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      date: { type: "number", multipleOf: 1 },
      updated: { type: "number", multipleOf: 1 },
      description: { type: "string", maxLength: 280 },
      title: { type: "string", minLength: 1, maxLength: 100 },
      type: { type: "string" },
      reply_to: { type: "string" },
      repost: { type: "string" },
      reply: { type: "boolean" },
      quote: { type: "boolean" },
      parents: {
        type: "array",
        items: { type: "string", pattern: "^[0-9a-zA-Z]{32,32}$" },
      },
      hashes: { type: "array", items: { type: "string" } },
      mentions: { type: "array", items: { type: "string" } },
      pt: { type: "number" },
      ptts: { type: "number", multipleOf: 1 },
      last_like: { type: "number", multipleOf: 1 },
      likes: { type: "number", multipleOf: 1 },
      reposts: { type: "number", multipleOf: 1 },
      quotes: { type: "number", multipleOf: 1 },
      comments: { type: "number", multipleOf: 1 },
    },
  },
  users: {
    type: "object",
    required: ["address", "invited_by"],
    properties: {
      address: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      invited_by: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      name: { type: "string", minLength: 1, maxLength: 50 },
      handle: { type: "string", minLength: 3, maxLength: 15 },
      image: { type: "string" },
      cover: { type: "string" },
      description: { type: "string", maxLength: 280 },
      hashes: { type: "array", items: { type: "string" } },
      mentions: { type: "array", items: { type: "string" } },
      followers: { type: "number", multipleOf: 1 },
      following: { type: "number", multipleOf: 1 },
      invites: { type: "number", multipleOf: 1 },
      invited: { type: "number", multipleOf: 1 },
    },
  },
  timeline: {
    type: "object",
    required: ["rid", "aid", "date", "broadcast"],
    properties: {
      date: { type: "number", multipleOf: 1 },
      rid: { type: "string" },
      aid: { type: "string", pattern: "^[0-9a-z]{32,32}$" },
      braodcast: {
        type: "array",
        items: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      },
    },
  },
  follows: {
    type: "object",
    required: ["date", "from", "to"],
    properties: {
      date: { type: "number", multipleOf: 1 },
      from: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      to: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      last: { type: "number", multipleOf: 1 },
    },
  },
  likes: {
    type: "object",
    required: ["date", "user", "aid"],
    properties: {
      date: { type: "number", multipleOf: 1 },
      user: { type: "string", pattern: "^[0-9a-zA-Z]{42,42}$" },
      aid: { type: "string", pattern: "^[0-9a-z]{32,32}$" },
    },
  },
}
