
.PHONY: dev
dev: format
	pnpm dev

.PHONY: dev2
dev2:install format
	pnpm dev2

.PHONY: dev4
dev4: format
	pnpm dev4


.PHONY: dev3
dev3:install format
	pnpm dev3

.PHONY: format
format: install
	pnpm format

.PHONY: install
install:
	pnpm i
